name: zilla
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - astroid=2.2.5
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - decorator=4.4.0
  - django=2.2
  - django-extensions=2.1.7
  - djangorestframework=3.9.4
  - entrypoints=0.3
  - faker=1.0.7
  - flake8=3.7.7
  - freetype=2.9.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - isort=4.3.17
  - jedi=0.13.3
  - jpeg=9b
  - krb5=1.16.1
  - lazy-object-proxy=1.3.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libpq=11.2
  - libtiff=4.0.10
  - mccabe=0.6.1
  - more-itertools=7.0.0
  - mypy=0.701
  - mypy_extensions=0.4.1
  - ncurses=6.1
  - nodejs=11.14.0
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - openssl=1.1.1b
  - parso=0.4.0
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1
  - pluggy=0.9.0
  - postgresql=11.2
  - prompt_toolkit=2.0.9
  - psutil=5.4.8
  - psycopg2=2.7.6.1
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - pygments=2.4.0
  - pylint=2.3.1
  - pylint-django=2.0.9
  - pylint-plugin-utils=0.5
  - pytest=4.4.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - sqlparse=0.3.0
  - text-unidecode=1.2
  - tk=8.6.8
  - tqdm=4.32.1
  - traitlets=4.3.2
  - typed-ast=1.3.5
  - typing=3.6.4
  - wcwidth=0.1.7
  - wheel=0.33.1
  - wrapt=1.11.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - appdirs==1.4.3
      - black==19.3b0
      - click==7.0
      - toml==0.10.0
