# Generated by Django 2.2.1 on 2019-06-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_type',
            new_name='type',
        ),
    ]
