# Generated by Django 2.2.1 on 2019-06-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20190611_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='type',
            new_name='business_type',
        ),
    ]
